package com.tefisoft.efiweb.entidad;
// Generated 04/07/2017 12:24:16 by Hibernate Tools 4.3.1


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.math.BigDecimal;

/**
 * BrkTRubros generated by hbm2java
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Table(name = "BRK_T_RUBROS")
public class BrkTRubros implements java.io.Serializable {

    @Id
    private Integer cdRubro;
    private Integer brkTCompania;
    private String dscRubro;
    private BigDecimal pctRubro;
    private BigDecimal factor;
    private BigDecimal valorRubro;
    private Character automatico;
    private Boolean codigo;


}


