package com.tefisoft.efiweb.entidad;
// Generated 04/07/2017 12:24:16 by Hibernate Tools 4.3.1


import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;

/**
 * BrkTCaracteristicas generated by hbm2java
 */
@Entity
@Table(name = "BRK_T_CARACTERISTICAS")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@IdClass(BrkTCaracteristicas.BrkTCaracteristicasId.class)
public class BrkTCaracteristicas implements java.io.Serializable {


    @Id
    private Integer cdCompania;
    @Id
    private Integer cdCaracteristica;
    private Integer cdObjCotizacion;
    private String dscCaracteristica;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CD_RUBRO")
    private BrkTRubros rubros;


    @Getter
    @Setter
    @AllArgsConstructor
    @NoArgsConstructor
    public static class BrkTCaracteristicasId implements java.io.Serializable {

        @Column(name = "CD_COMPANIA", nullable = false, precision = 22, scale = 0)
        private Integer cdCompania;
        @Column(name = "CD_CARACTERISTICA", nullable = false, precision = 22, scale = 0)
        private Integer cdCaracteristica;

        public boolean equals(Object other) {
            if ((this == other)) return true;
            if ((other == null)) return false;
            if (!(other instanceof BrkTCaracteristicasId)) return false;
            BrkTCaracteristicasId castOther = (BrkTCaracteristicasId) other;

            return ((this.getCdCompania() == castOther.getCdCompania()) || (this.getCdCompania() != null && castOther.getCdCompania() != null && this.getCdCompania().equals(castOther.getCdCompania())))
                    && ((this.getCdCaracteristica() == castOther.getCdCaracteristica()) || (this.getCdCaracteristica() != null && castOther.getCdCaracteristica() != null && this.getCdCaracteristica().equals(castOther.getCdCaracteristica())));
        }

        public int hashCode() {
            int result = 17;

            result = 37 * result + (getCdCompania() == null ? 0 : this.getCdCompania().hashCode());
            result = 37 * result + (getCdCaracteristica() == null ? 0 : this.getCdCaracteristica().hashCode());
            return result;
        }

    }


}


