SELECT
  A.CD_COTIZACION,
  A.CD_CLIENTE,
  A.CD_MONEDA,
  A.CD_AGENTE,
  A.CD_COMPANIA,
  A.NUM_COTIZACION,
  A.DIAS_VIGENCIA,
  A.CD_ASEGURADORA,
  A.GIRO_NEGOCIO,
  A.CD_PROSPECTO,
  A.TIPO -- a.cd
FROM BRK_T_COTIZACIONES A
WHERE A.CD_COMPANIA = 1
      AND A.CD_COTIZACION = 121611;

--121611
--- ramosCotizacion
SELECT
  rc.CD_RAMO_COTIZACION,
  rc.CD_RAM_COT_ORI,
  rc.TOT_ASEGURADO,
  rc.CD_COMPANIA,
  rc.POLIZA,
  rc.FC_DESDE,
  rc.FC_HASTA,
  r.NM_RAMO
FROM BRK_T_RAMOS_COTIZACION rc INNER JOIN BRK_T_RAMOS r ON rc.CD_RAMO = r.CD_RAMO AND rc.CD_COMPANIA = r.CD_COMPANIA
WHERE rc.CD_COMPANIA = 1
      AND rc.CD_RAMO_COTIZACION = 135367
      AND (rc.CD_COTIZACION NOT IN (SELECT CD_COTIZACION
                                    FROM BRK_t_COTIZACIONES
                                    WHERE CD_COMPANIA = 1 AND
                                          (TIPO LIKE 'RASA' OR TIPO LIKE 'AJUSTE')));

-- ubicacion

SELECT DISTINCT
  u.CD_RAMO_COTIZACION,
  u.DSC_UBICACION,
  u.CD_COMPANIA,
  u.CD_UBICACION,
  u.VAL_ASEGURADO,
  NVL(u.TOT_ASE_ACTUAL, u.TOT_ASEGURADO) TOT_ASEGURADO,
  u.TASA,
  u.FACTOR,
  u.VAL_PRIMA,
  u.ITEM,
  rc.fc_desde,
  rc.fc_hasta,
  F_NUM_VAL_ASEGURADO_UBC(u.CD_COMPANIA, u.CD_UBICACION, rc.fc_desde,
                          rc.fc_hasta)   VAL_ASEG_UBC
FROM BRK_T_UBICACION u, brk_t_ramos_cotizacion rc
WHERE u.Cd_Compania = rc.cd_compania
      AND u.cd_ramo_cotizacion = rc.cd_ramo_cotizacion
      AND (u.CD_COMPANIA = :COMPANIA)
      AND (rc.CD_RAMO_COTIZACION = :RAMO_COT)
      AND u.activo = 1
      AND F_NUM_CONT_OBJ_ACT(u.CD_COMPANIA, u.CD_UBICACION, rc.fc_desde,
                             rc.fc_hasta) > 0
UNION
SELECT DISTINCT
  u.CD_RAMO_COTIZACION,
  u.DSC_UBICACION,
  u.CD_COMPANIA,
  u.CD_UBICACION,
  u.VAL_ASEGURADO,
  NVL(u.TOT_ASE_ACTUAL, u.TOT_ASEGURADO) TOT_ASEGURADO,
  u.TASA,
  u.FACTOR,
  u.VAL_PRIMA,
  u.ITEM,
  rc.fc_desde,
  rc.fc_hasta,
  F_NUM_VAL_ASEGURADO_UBC(u.CD_COMPANIA, u.CD_UBICACION, rc.fc_desde,
                          rc.fc_hasta)   VAL_ASEG_UBC
FROM BRK_T_UBICACION u, brk_t_ramos_cotizacion rc /*, brk_t_obj_cotizacion             */
WHERE u.Cd_Compania = rc.cd_compania
      AND u.cd_ramo_cotizacion = rc.cd_ramo_cotizacion
      AND (u.CD_COMPANIA = :COMPANIA)
      AND (rc.cd_ram_cot_ori = :RAMO_COT)
      AND u.activo = 1
      AND F_NUM_CONT_OBJ_ACT(u.CD_COMPANIA, u.CD_UBICACION, rc.fc_desde,
                             rc.fc_hasta) > 0
      AND u.cd_ubica_org IS NULL;

-- objeto cdUbicacion: 121179
SELECT
  o.DSC_OBJETO,
  o.VAL_ASEGURADO,
  o.CD_OBJ_COTIZACION,
  o.VAL_PRIMA,
  o.FACTOR,
  o.ITEM,
  o.OBS_OBJETO,
  o.CD_COMPANIA,
  to_number(o.TASA)                     TASA,
  o.TOT_ASEGURADO,
  NVL(o.TOT_ASEGURADO, o.VAL_ASEGURADO) TOT_ASEGURADO1,
  o.CD_UBICACION
FROM BRK_T_OBJ_COTIZACION o, brk_t_ramos_cotizacion rc, brk_t_cotizaciones c
WHERE c.CD_COMPANIA = rc.CD_COMPANIA
      AND c.cd_cotizacion = rc.cd_cotizacion
      AND o.CD_COMPANIA = rc.CD_COMPANIA
      AND o.cd_ramo_cotizacion = rc.cd_ramo_cotizacion
      AND c.tipo NOT LIKE '%CANCEL%'
      AND c.tipo NOT LIKE '%AJUSTE%'
      AND c.tipo NOT LIKE '%ANUL%'
      AND o.DSC_OBJETO <> 'R.A.S.A.'
      AND o.ACTIVO = 1
      AND o.CD_COMPANIA = :COMPANIA
      AND (o.CD_UBICACION IN (SELECT CD_UBICACION
                              FROM brk_t_ubicacion
                              WHERE (CD_UBICACION = :UBICA OR cd_ubica_org = :UBICA)
                                    AND cd_compania = :COMPANIA))


ORDER BY o.CD_OBJ_COTIZACION ASC;

-- caractersiticas

SELECT
  c.DSC_CARACTERISTICA,
  r.DSC_RUBRO
FROM BRK_T_CARACTERISTICAS c,
  BRK_T_RUBROS r
WHERE (c.CD_RUBRO = r.CD_RUBRO) AND
      (c.CD_COMPANIA = :compania) AND
      (c.CD_OBJ_COTIZACION = :obj_cotiza) AND
      r.CD_COMPANIA = (SELECT NVL(REF_MATRIZ, CD_COMPANIA)
                       FROM BRK_T_COMPANIA
                       WHERE CD_COMPANIA = :compania)
UNION
SELECT
  v.DSC_CARACTERISTICA,
  v.DSC_RUBRO
FROM V_BRK_OBJ_CAR_VEHICULOS v
WHERE v.CD_COMPANIA = :compania
      AND v.CD_OBJ_COTIZACION = :obj_cotiza
      AND v.DSC_CARACTERISTICA IS NOT NULL;

-- subojeto
SELECT
  s.CD_SUBOBJETO,
  s.DSC_SUBOBJETO,
  s.TASA,
  s.VAL_PRIMA,
  s.VAL_ASEGURADO,
  s.OBS_SUBOBJETO,
  s.ITEM
FROM BRK_T_SUBOBJETOS s
WHERE (s.CD_COMPANIA = :al_compania) AND
      (s.CD_OBJ_COTIZACION = :al_objcot)
ORDER BY s.ITEM ASC;

---
---COBERTURAS
SELECT
  cn.VAL_LIMITE,
  cn.COB_ADICIONAL,
  cn.VAL_PRIMA,
  cn.TASA,
  cn.ORD_IMPRESION,
  c.NM_COBERTURA,
  cn.OBS_COB_NEGOCIO,
  cn.CD_RUBRO
FROM BRK_T_COBERTURAS_NEGOCIO cn,
  BRK_T_COBERTURAS c
WHERE (cn.CD_COMPANIA = 1)
      AND (c.CD_COMPANIA = (SELECT NVL(REF_MATRIZ, CD_COMPANIA)
                            FROM BRK_T_COMPANIA
                            WHERE CD_COMPANIA = 1))
      --AND (cn.COB_ADICIONAL IS NULL)
      AND (cn.ADICIONAL_RAMO IS NULL OR cn.ADICIONAL_RAMO <> 'X')
      AND (cn.ACTIVO = 1)
      AND (cn.CD_RAMO_COTIZACION = 135367)
      AND (cn.CD_OBJ_COTIZACION IS NULL)
      AND (cn.CD_COBERTURA = c.CD_COBERTURA)
ORDER BY cn.ORD_IMPRESION;

-- cobertyuras adc
SELECT
  cn.VAL_LIMITE,
  cn.COB_ADICIONAL,
  cn.VAL_PRIMA,
  cn.TASA,
  cn.ORD_IMPRESION,
  c.NM_COBERTURA,
  cn.OBS_COB_NEGOCIO,
  cn.CD_RUBRO
FROM BRK_T_COBERTURAS_NEGOCIO cn,
  BRK_T_COBERTURAS c
WHERE (c.CD_COMPANIA = (SELECT NVL(REF_MATRIZ, CD_COMPANIA)
                        FROM BRK_T_COMPANIA
                        WHERE CD_COMPANIA = 1)) AND
      (cn.CD_COMPANIA = 1) AND
      (cn.ADICIONAL_RAMO = 'X') AND
      (cn.ACTIVO = 1) AND
      (cn.CD_RAMO_COTIZACION = 135367) AND
      (c.CD_COBERTURA = cn.CD_COBERTURA)
ORDER BY cn.ORD_IMPRESION;

--CLAUSULAS
SELECT
  cl.VAL_LIMITE,
  cl.VAL_PRIMA,
  cl.TASA,
  cl.ORD_IMPRESION,
  c.NM_CLAUSULA,
  cl.OBS_CLAUSULAS_NEGOCIO
FROM BRK_T_CLAUSULAS_NEGOCIO cl,
  BRK_T_CLAUSULAS c
WHERE cl.CD_COMPANIA = :compania
      AND (c.CD_COMPANIA = (SELECT NVL(REF_MATRIZ, CD_COMPANIA)
                            FROM BRK_T_COMPANIA
                            WHERE CD_COMPANIA = :compania))
      AND (cl.ADICIONAL_RAMO IS NULL OR cl.ADICIONAL_RAMO <> 'X')
      AND cl.ACTIVO = 1
      AND cl.CD_RAMO_COTIZACION = :ramo
      AND cl.CD_CLAUSULA = c.CD_CLAUSULA
ORDER BY cl.ORD_IMPRESION;

-- CLAUSUALAS ADC
SELECT
  cl.VAL_LIMITE,
  cl.VAL_PRIMA,
  cl.TASA,
  cl.ORD_IMPRESION,
  c.NM_CLAUSULA,
  cl.OBS_CLAUSULAS_NEGOCIO
FROM BRK_T_CLAUSULAS_NEGOCIO cl,
  BRK_T_CLAUSULAS c
WHERE cl.CD_COMPANIA = :compania
      AND (c.CD_COMPANIA = (SELECT NVL(REF_MATRIZ, CD_COMPANIA)
                            FROM BRK_T_COMPANIA
                            WHERE CD_COMPANIA = :compania))
      AND cl.ADICIONAL_RAMO = 'X'
      AND cl.ACTIVO = 1
      AND cl.CD_RAMO_COTIZACION = :ramo
      AND cl.CD_CLAUSULA = c.CD_CLAUSULA
ORDER BY cl.ORD_IMPRESION;

--- COBERTURAS ESPECIALES POR UBICACION

SELECT
  u.CD_UBICACION,
  u.DSC_UBICACION,
  c.NM_COBERTURA,
  cn.CD_COB_NEGOCIO,
  cn.VAL_LIMITE,
  cn.COB_ADICIONAL,
  cn.VAL_PRIMA,
  cn.TASA,
  cn.FACTOR,
  cn.ORD_IMPRESION,
  u.ITEM,
  cn.OBS_COB_NEGOCIO
FROM BRK_T_COBERTURAS_NEGOCIO cn,
  BRK_T_UBICACION u,
  BRK_T_COBERTURAS c
WHERE u.CD_UBICACION = cn.CD_UBICACION
      AND cn.CD_COMPANIA = u.CD_COMPANIA
      AND c.CD_COBERTURA = cn.CD_COBERTURA
      AND ((cn.COB_ADICIONAL IS NULL)
           AND (u.CD_RAMO_COTIZACION = :ramo)
           AND (u.CD_COMPANIA = :compania)
           AND (cn.ACTIVO = '1'))
      AND c.CD_COMPANIA = (SELECT NVL(REF_MATRIZ, CD_COMPANIA)
                           FROM BRK_T_COMPANIA
                           WHERE CD_COMPANIA = :compania)
ORDER BY u.ITEM, cn.ORD_IMPRESION;

-- COBERTURAS ESPECIALES POR OBJETO

SELECT
  u.CD_UBICACION,
  ob.CD_OBJ_COTIZACION,
  u.DSC_UBICACION,
  ob.DSC_OBJETO,

  c.NM_COBERTURA,
  cn.CD_COB_NEGOCIO,
  cn.VAL_LIMITE,
  cn.COB_ADICIONAL,
  cn.VAL_PRIMA,
  cn.TASA,
  cn.FACTOR,
  cn.ORD_IMPRESION,
  u.ITEM,
  cn.OBS_COB_NEGOCIO
FROM BRK_T_COBERTURAS_NEGOCIO cn,
  BRK_T_OBJ_COTIZACION ob,
  BRK_T_UBICACION u,
  BRK_T_COBERTURAS c
WHERE ob.CD_COMPANIA = cn.CD_COMPANIA
      AND ob.CD_OBJ_COTIZACION = cn.CD_OBJ_COTIZACION
      AND u.CD_COMPANIA = ob.CD_COMPANIA
      AND u.CD_UBICACION = ob.CD_UBICACION
      AND cn.CD_COMPANIA = ob.CD_COMPANIA
      AND (c.CD_COMPANIA = (SELECT NVL(REF_MATRIZ, CD_COMPANIA)
                            FROM BRK_T_COMPANIA
                            WHERE CD_COMPANIA = :compania))
      AND c.CD_COBERTURA = cn.CD_COBERTURA
      AND (u.CD_RAMO_COTIZACION = :ramo
           AND u.CD_COMPANIA = :compania
           AND cn.CD_UBICACION IS NULL
           AND cn.COB_ADICIONAL IS NULL
           AND cn.ACTIVO = 1)
ORDER BY u.ITEM, ob.DSC_OBJETO, cn.ORD_IMPRESION;

-- CLAUSULAS ESPECIALES POR UBICACION

SELECT
  u.CD_UBICACION,
  u.DSC_UBICACION,
  cl.VAL_LIMITE,
  cl.VAL_PRIMA,
  cl.TASA,
  cl.ORD_IMPRESION,
  c.NM_CLAUSULA,
  cl.OBS_CLAUSULAS_NEGOCIO,
  u.ITEM
FROM BRK_T_CLAUSULAS_NEGOCIO cl,
  BRK_T_UBICACION u,
  BRK_T_CLAUSULAS c
WHERE u.CD_UBICACION = cl.CD_UBICACION
      AND u.CD_COMPANIA = cl.CD_COMPANIA
      AND c.CD_CLAUSULA = cl.CD_CLAUSULA
      AND (u.CD_COMPANIA = :compania
           AND u.CD_RAMO_COTIZACION = :ramo
           AND cl.CD_RAMO_COTIZACION IS NULL
           AND cl.ACTIVO = 1)
      AND c.CD_COMPANIA = (SELECT NVL(REF_MATRIZ, CD_COMPANIA)
                           FROM BRK_T_COMPANIA
                           WHERE CD_COMPANIA = :compania)
ORDER BY u.ITEM, cl.ORD_IMPRESION;

-- CLAUSULAS ESPECIALES POR OBJETO

SELECT
  u.CD_UBICACION,
  ob.CD_OBJ_COTIZACION,
  u.DSC_UBICACION,
  ob.DSC_OBJETO,
  cl.VAL_LIMITE,
  cl.VAL_PRIMA,
  cl.TASA,
  cl.ORD_IMPRESION,
  c.NM_CLAUSULA,
  cl.OBS_CLAUSULAS_NEGOCIO,
  u.ITEM
FROM BRK_T_CLAUSULAS_NEGOCIO cl,
  BRK_T_UBICACION u,
  BRK_T_OBJ_COTIZACION ob,
  BRK_T_CLAUSULAS c
WHERE (u.CD_COMPANIA = cl.CD_COMPANIA) AND
      (ob.CD_COMPANIA = u.CD_COMPANIA) AND
      (ob.CD_UBICACION = u.CD_UBICACION) AND
      (ob.CD_COMPANIA = cl.CD_COMPANIA) AND
      (ob.CD_OBJ_COTIZACION = cl.CD_OBJ_COTIZACION) AND
      (u.CD_COMPANIA = ob.CD_COMPANIA) AND
      (c.CD_COMPANIA = (SELECT NVL(REF_MATRIZ, CD_COMPANIA)
                        FROM BRK_T_COMPANIA
                        WHERE CD_COMPANIA = :compania)) AND
      (c.CD_CLAUSULA = cl.CD_CLAUSULA) AND
      ((u.CD_COMPANIA = :compania) AND
       (u.CD_RAMO_COTIZACION = :ramo) AND
       (cl.CD_RAMO_COTIZACION IS NULL) AND
       (cl.CD_UBICACION IS NULL) AND
       cl.ACTIVO = 1)
ORDER BY u.ITEM, ob.DSC_OBJETO, cl.ORD_IMPRESION;

--- GARANTIAS DE COBERTURA
SELECT
  g.NM_GARANTIA,
  gn.CD_GARANTIA,
  gn.FC_CREACION,
  gn.FC_MAX_CONDICIONADA,
  gn.FC_EFEC_CUMPLIMIENTO,
  gn.TIPO,
  gn.NUM_ANEXO,
  gn.OBS_GARANTIA_NEGOCIO,
  gn.ORD_IMPRESION
FROM BRK_T_GARANTIAS_NEGOCIO gn, BRK_T_GARANTIAS g
WHERE (gn.CD_GARANTIA = g.CD_GARANTIA)
      AND gn.CD_COMPANIA = :compania
      AND gn.CD_RAMO_COTIZACION = :ramo
      AND gn.ACTIVO = 1
ORDER BY gn.ORD_IMPRESION;

-- EXCLUSIONES
SELECT
  ex.DSC_EXCLUSION,
  ex.OBS_EXC_NEGOCIO,
  ex.ORD_IMPRESION
FROM BRK_T_EXCLUSIONES_NEGOCIO ex
WHERE ex.CD_COMPANIA = :compania
      AND ex.CD_RAMO_COTIZACION = :cd_ram_cot
ORDER BY ex.ORD_IMPRESION;

-- EXCLUSIONES POR UBICACION
SELECT
  u.CD_UBICACION,
  ex.DSC_EXCLUSION,
  ex.OBS_EXC_NEGOCIO,
  ex.ORD_IMPRESION,
  u.DSC_UBICACION,
  u.ITEM
FROM BRK_T_EXCLUSIONES_NEGOCIO ex,
  BRK_T_RAMOS_COTIZACION rc,
  BRK_T_UBICACION u
WHERE rc.CD_COMPANIA = :compania
      AND rc.CD_COMPANIA = u.CD_COMPANIA
      AND rc.CD_RAMO_COTIZACION = :cd_ram_cot
      AND rc.CD_RAMO_COTIZACION = u.CD_RAMO_COTIZACION
      AND u.CD_COMPANIA = ex.CD_COMPANIA
      AND u.CD_UBICACION = ex.CD_UBICACION
ORDER BY ex.ORD_IMPRESION;

-- EXCLUSIONES POR ITEM
SELECT
  u.CD_UBICACION,
  ob.CD_OBJ_COTIZACION,
  ex.DSC_EXCLUSION,
  ex.OBS_EXC_NEGOCIO,
  ob.DSC_OBJETO,
  ex.ORD_IMPRESION,
  u.DSC_UBICACION,
  u.ITEM,
  ob.ITEM
FROM BRK_T_EXCLUSIONES_NEGOCIO ex,
  BRK_T_OBJ_COTIZACION ob,
  BRK_T_RAMOS_COTIZACION rc,
  BRK_T_UBICACION u
WHERE rc.CD_COMPANIA = :compania
      AND rc.CD_COMPANIA = u.CD_COMPANIA
      AND rc.CD_RAMO_COTIZACION = :cd_ram_cot
      AND rc.CD_RAMO_COTIZACION = u.CD_RAMO_COTIZACION
      AND u.CD_COMPANIA = ob.CD_COMPANIA
      AND u.CD_UBICACION = ob.CD_UBICACION
      AND ob.CD_COMPANIA = ex.CD_COMPANIA
      AND ob.CD_OBJ_COTIZACION = ex.CD_OBJ_COTIZACION
ORDER BY u.ITEM, ob.ITEM, ex.ORD_IMPRESION;

--- NOTAS ACLARATORIAS
SELECT
  al.TXT_ACLARATORIO,
  al.NUM_ACLARATORIO
FROM BRK_T_ACLARATORIOS al
WHERE al.ACTIVO = 1
      AND al.CD_RAMO_COTIZACION = 146114
      AND al.CD_COMPANIA = 1
      AND NVL(al.IMPRIME, 0) = 1
ORDER BY al.NUM_ACLARATORIO;

-- DEDUCIBLES DEL RAMO
SELECT
  d.CD_DEDUCIBLE,
  d.PCT_V_ASEG,
  d.PCT_RECLAMO,
  d.VAL_MINIMO,
  d.VAL_FIJO,
  d.OBS_DEDUCIBLE
FROM BRK_T_DEDUCIBLES d
WHERE d.CD_RAMO_COTIZACION = 135367
      AND d.CD_COMPANIA = 1
      AND d.ACTIVO = 1;

-- DEDUCIBLES POR COBERTURA
SELECT
  c.CD_COBERTURA,
  c.NM_COBERTURA,
  d.PCT_V_ASEG,
  d.PCT_RECLAMO,
  d.VAL_MINIMO,
  d.VAL_FIJO,
  d.OBS_DEDUCIBLE
FROM BRK_T_COBERTURAS_NEGOCIO cn,
  BRK_T_DEDUCIBLES d,
  BRK_T_COBERTURAS c
WHERE cn.CD_COMPANIA = :compania
      AND cn.CD_COMPANIA = d.CD_COMPANIA
      AND cn.CD_RAMO_COTIZACION = :ramo
      AND cn.CD_COB_NEGOCIO = d.CD_COB_NEGOCIO
      AND cn.CD_COBERTURA = c.CD_COBERTURA
      AND c.cd_compania = (SELECT NVL(REF_MATRIZ, CD_COMPANIA)
                           FROM BRK_T_COMPANIA
                           WHERE CD_COMPANIA = :compania);


SELECT *
FROM BRK_T_UBICACION
WHERE CD_UBICACION = 2;

-- test VH: 130972/146114
SELECT *
FROM BRK_T_RAMOS_COTIZACION rc
WHERE rc.CD_RAMO_COTIZACION = 146114;

SELECT *
FROM BRK_T_COTIZACIONES c
WHERE c.TIPO = 'C_MAESTRA'
ORDER BY c.CD_COTIZACION DESC;

-- planes
SELECT
  u.CD_UBICACION,
  u.ITEM,
  u.DSC_UBICACION,
  p.DSC_PLAN
FROM BRK_T_UBICACION u INNER JOIN BRK_T_PLANES p ON u.CD_PLAN = p.CD_PLAN AND u.CD_COMPANIA = p.CD_COMPANIA
WHERE u.ACTIVO = 1
      AND u.CD_RAMO_COTIZACION = ?
      AND u.CD_COMPANIA = ?
ORDER BY u.ITEM;

-- VAM
-- cobertura by PLAN

SELECT
  c.VAL_LIMITE,
  c.VAL_PRIMA,
  c.ORD_IMPRESION,
  b.NM_COBERTURA,
  c.OBS_COB_NEGOCIO,
  r.DSC_RUBRO
FROM brk_t_coberturas_negocio c INNER JOIN BRK_T_COBERTURAS b ON c.CD_COBERTURA = b.CD_COBERTURA
  LEFT JOIN BRK_T_RUBROS r ON c.CD_RUBRO = r.CD_RUBRO AND c.CD_COMPANIA = r.CD_COMPANIA
WHERE nvl(c.estado, '0') <> 'X'
      AND c.ACTIVO = 1
      AND c.CD_COMPANIA = 1
      AND c.CD_UBICACION = 128663
ORDER BY c.ORD_IMPRESION;

SELECT
  cn.VAL_LIMITE,
  cn.VAL_PRIMA,
  cn.ORD_IMPRESION,
  c.NM_COBERTURA,
  cn.OBS_COB_NEGOCIO
--r.DSC_RUBRO
FROM BRK_T_COBERTURAS_NEGOCIO cn,
  BRK_T_COBERTURAS c
--BRK_T_RUBROS r
WHERE cn.CD_COMPANIA = 1
      -- AND cn.CD_RUBRO = r.CD_RUBRO(+)
      --AND cn.CD_COMPANIA = r.CD_COMPANIA
      --       AND (c.CD_COMPANIA = (SELECT NVL(REF_MATRIZ, CD_COMPANIA)
      --                             FROM BRK_T_COMPANIA
      --                             WHERE CD_COMPANIA = 1))

      -- AND (cn.ADICIONAL_RAMO IS NULL OR cn.ADICIONAL_RAMO <> 'X')
      AND cn.ACTIVO = 1
      AND cn.CD_UBICACION = 128663
      --AND cn.CD_OBJ_COTIZACION IS NULL
      AND cn.CD_COBERTURA = c.CD_COBERTURA
ORDER BY cn.ORD_IMPRESION;

-- EXCLUSIONES POR PLAN
SELECT
  ex.DSC_EXCLUSION,
  ex.OBS_EXC_NEGOCIO,
  ex.ORD_IMPRESION
FROM BRK_T_EXCLUSIONES_NEGOCIO ex
WHERE ex.CD_COMPANIA = ?
      AND ex.CD_UBICACION = ?
      AND ex.ACTIVO = 1
--ORDER BY ex.ORD_IMPRESION
UNION
SELECT
  ex.DSC_EXCLUSION,
  ex.OBS_EXC_NEGOCIO,
  ex.ORD_IMPRESION
FROM brk_t_exclusiones_negocio ex,
  brk_t_coberturas_negocio b
WHERE ex.cd_compania = b.cd_compania
      AND ex.cd_cob_negocio = b.cd_cob_negocio
      AND ex.activo = 1
      AND ex.cd_compania = ?
      AND b.cd_ubicacion = ?
ORDER BY ORD_IMPRESION;

-- FORMA DE PRIMA ASISTENCIA MEDICA
SELECT
  f.CD_FORMA_PRIMA,
  b.DSC_RUBRO,
  f.VAL_FORMA_PRIMA,
  f.PERIODO,
  f.VAL_TARJETA
FROM BRK_T_FORMA_PRIMA f LEFT JOIN BRK_T_RUBROS b ON f.CD_COMPANIA = b.CD_COMPANIA AND f.CD_RUBRO = b.CD_RUBRO
WHERE f.CD_COMPANIA = ? AND f.CD_UBICACION = ?
ORDER BY f.CD_FORMA_PRIMA;

-- EXCLUSIONES POR RAMO
SELECT
  ex.DSC_EXCLUSION,
  ex.OBS_EXC_NEGOCIO,
  ex.ORD_IMPRESION
FROM BRK_T_EXCLUSIONES_NEGOCIO ex
WHERE ex.CD_COMPANIA = ?
      AND ex.CD_RAMO_COTIZACION = ?
      AND ex.ACTIVO = 1
UNION
SELECT
  ex.DSC_EXCLUSION,
  ex.OBS_EXC_NEGOCIO,
  ex.ORD_IMPRESION
FROM brk_t_exclusiones_negocio ex,
  brk_t_coberturas_negocio b
WHERE ex.cd_compania = b.cd_compania
      AND ex.cd_cob_negocio = b.cd_cob_negocio
      AND ex.activo = 1
      AND ex.cd_compania = ?
      AND b.CD_RAMO_COTIZACION = ?
ORDER BY ORD_IMPRESION;

-- FORMA PRIMA VIDA
SELECT DISTINCT
  val_asegurado,
  tasa,
  factor,
  val_prima
FROM BRK_T_OBJ_COTIZACION
WHERE cd_compania = :al_cd_compania
      AND cd_ubicacion = :al_cd_ubc;

-- asegurados

SELECT
  o.CD_OBJ_COTIZACION,
  o.CEDULA_O,
  o.DSC_OBJETO,
  o.FC_NACIMIENTO,
  o.TIPO,
  o.TOT_PRI_ACTUAL,
  o.ITEM,
  o.ACTIVO
FROM BRK_T_OBJ_COTIZACION o
WHERE o.CD_UBICACION = 129151 AND o.CD_COMPANIA = 1;

--DEPENDIENTES
SELECT
  s.CD_SUBOBJETO,
  s.CEDULA_S,
  s.DSC_SUBOBJETO,
  s.FC_NACIMIENTO,
  s.BENEFICIO,
  s.ITEM,
  s.ACTIVO,
  s.OBS_SUBOBJETO
FROM BRK_T_SUBOBJETOS s
WHERE s.CD_COMPANIA = ? AND s.CD_OBJ_COTIZACION = ?
ORDER BY s.DSC_SUBOBJETO;

-- test 130735/145830/129151 - 119089/140299

--****************************************************************************************************
--SINIESTROS
-- test gen 35140 / obj: 740947

-- encabezado
SELECT
  s.CD_CLIENTE,
  c.NM_CLIENTE || ' ' || NVL(c.AP_CLIENTE, '') AS CLIENTE,
  s.NUM_SINIESTRO,
  s.CD_RECLAMO,
  s.FC_CREACION,
  s.FC_SINIESTRO,
  s.CAUSA,
  s.OBS_SINIESTRO,
  s.POLIZA,
  s.NUM_REP_ASEG,
  s.NUM_ASEGURADORA,
  s.ANEXO,
  s.ANO_SINIESTRO,
  o.CD_OBJETO,
  o.DSC_OBJETO,
  o.VAL_ASEGURADO,
  g.NM_CLI_GRUPO,
  rc.FACT_ASEG,
  F_NM_ASEGURADORA(s.CD_ASEGURADORA)              ASEGURADORA,
  F_NM_USUARIO_SINIES(s.CD_USUARIO)               USUARIO,
  rc.FC_HASTA - SYSDATE                           ES_VIGENTE_A,
  SYSDATE - rc.FC_DESDE                           ES_VIGENTE_B,
  rc.FC_DESDE,
  rc.FC_HASTA,
  r.NM_RAMO
FROM BRK_T_OBJ_SINIESTRO o,
  BRK_T_SINIESTRO s,
  BRK_T_RAMOS_COTIZACION rc,
  BRK_T_CLI_GRUPO g, BRK_T_CLIENTES c, BRK_T_RAMOS r
WHERE s.CD_COMPANIA = o.CD_COMPANIA
      AND s.CD_RECLAMO = o.CD_RECLAMO
      AND s.CD_RAMO_COTIZACION = rc.CD_RAMO_COTIZACION
      AND s.CD_COMPANIA = rc.CD_COMPANIA
      AND rc.CD_CLI_GRUPO = g.CD_CLI_GRUPO (+)
      AND c.CD_CLIENTE = s.CD_CLIENTE
      AND c.CD_COMPANIA = s.CD_COMPANIA
      AND s.CD_RECLAMO = 35140
      AND s.CD_COMPANIA = 1
      AND rc.CD_RAMO = r.CD_RAMO AND rc.CD_COMPANIA = r.CD_COMPANIA;

-- objeto aseg
SELECT
  o.DSC_OBJETO,
  o.OBS_OBJETO,
  o.VAL_ASEGURADO,
  v.CD_OBJ_CAR_VEHICULO,
  v.ANIO_DE_FABRICACION,
  v.COLOR,
  v.MARCA,
  v.MODELO,
  v.NO_DE_CHASIS,
  v.NO_DE_MOTOR,
  v.NUM_ASIENTOS,
  v.PLACA,
  v.RANV_CPN,
  v.SEGUNDO_COLOR,
  v.TIPO_VEH,
  v.USO_VEHICULO
FROM BRK_T_OBJ_COTIZACION o LEFT JOIN BRK_T_OBJ_CAR_VEHICULOS v
    ON o.CD_OBJ_COTIZACION = v.CD_OBJ_COTIZACION AND o.CD_COMPANIA = v.CD_COMPANIA
WHERE o.CD_OBJ_COTIZACION = 740947;

--- insecciones
SELECT
  i.CD_INSPECCION,
  i.FC_INSPECCION,
  i.INSPECTOR,
  i.LUGAR,
  i.OBSERVACIONES
FROM BRK_T_INSPECCION i
WHERE i.CD_RECLAMO = 32002
      AND i.CD_COMPANIA = 1;
--ORDER BY i.CD_INSPECCION;

--docu u2611 : u2610
SELECT
  ROWNUM,
  d.CD_DOC_SINIESTRO,
  t.NM_DOCUMENTO,
  d.OBS_DOC_SINIESTRO,
  d.RECIBO,
  d.FC_RECIBO_BRK,
  d.FC_ENVIO_ASEG
FROM BRK_T_DOC_SINIESTRO d LEFT JOIN BRK_T_TP_DOC_SINIESTRO t
    ON d.CD_TP_DOC_SINIESTRO = t.CD_TP_DOC_SINIESTRO
WHERE d.CD_RECLAMO = 35140
      AND d.CD_COMPANIA = 1
ORDER BY d.CD_DOC_SINIESTRO;

-- deducible
SELECT
  d.CD_COB_DED_SINIESTRO,
  d.NM_COBERTURA,
  d.VAL_LIMITE,
  d.PCT_RECLAMO,
  d.PCT_V_ASEG,
  d.VAL_MINIMO,
  d.VAL_FIJO,
  d.OBSERVACIONES
FROM BRK_T_COB_DED_SINIESTRO d
WHERE d.CD_RECLAMO = 35140
      AND d.CD_COMPANIA = 1
ORDER BY d.CD_COB_DED_SINIESTRO;

-- liquidacion
SELECT
  s.CD_PAGO,
  s.FORMA_PAGO,
  s.FC_PAGO,
  s.VAL_PAGO,
  s.FC_DOC_PAGO,
  s.BANCO,
  s.CHEQUE,
  s.CTA_CTE,
  r.DSC_RUBRO,
  s.OBS_PAGO,
  s.FC_PAGO_SOL
FROM BRK_T_PAGO_SINIESTRO s
  LEFT JOIN BRK_T_TABLAS_RUBRO tr
    ON tr.CD_TAB_RUBRO = s.CD_RUBRO AND tr.CD_COMPANIA = s.CD_COMPANIA
  LEFT JOIN BRK_T_TABLAS t
    ON t.CD_TABLA = tr.CD_TABLA
  LEFT JOIN BRK_T_RUBROS r
    ON r.CD_RUBRO = tr.CD_RUBRO
WHERE s.CD_RECLAMO = 32002
      AND s.CD_COMPANIA = 1
      AND t.NM_TABLA LIKE '%BRK_T_LIQUIDA_SIN%'
ORDER BY s.FC_PAGO_SOL;

SELECT
  tr.CD_TAB_RUBRO,
  tr.CD_COMPANIA,
  r.DSC_RUBRO
FROM BRK_T_RUBROS r,
  BRK_T_TABLAS,
  BRK_T_TABLAS_RUBRO tr
WHERE (tr.CD_TABLA = BRK_T_TABLAS.CD_TABLA)
      AND (tr.CD_RUBRO = r.CD_RUBRO)
      AND ((BRK_T_TABLAS.NM_TABLA LIKE '%BRK_T_LIQUIDA_SIN%'))
      AND tr.CD_TAB_RUBRO = 13;

--estado

SELECT
  s.FC_SEGUIMIENTO,
  e.DSC_ESTADO,
  s.CARTA,
  s.OBSERVACION,
  s.ACTIVO,
  s.ENV_ASEG
FROM BRK_T_SEG_SINIESTRO s INNER JOIN BRK_T_EST_SINIESTRO e
    ON s.CD_EST_SINIESTRO = e.CD_EST_SINIESTRO
WHERE s.CD_COMPANIA = 1
      AND s.CD_RECLAMO = 35140
      AND s.ACTIVO = 1;

-- *****************************************
-- siniestros vam
SELECT
  s.CD_CLIENTE,
  c.NM_CLIENTE || ' ' || NVL(c.AP_CLIENTE, '') AS CLIENTE,
  s.NUM_SINIESTRO,
  s.CD_RECLAMO,
  s.CD_RAMO,
  s.CD_RAMO_COTIZACION,
  s.FC_CREACION,
  s.FC_SINIESTRO,
  s.CAUSA,
  s.OBS_SINIESTRO,
  s.POLIZA,
  s.NUM_REP_ASEG,
  s.NUM_ASEGURADORA,
  s.ANEXO,
  s.ANO_SINIESTRO,
  s.CD_COMPANIA,
  os.VAL_ASEGURADO,
  g.NM_CLI_GRUPO,
  rc.FACT_ASEG,
  F_NM_ASEGURADORA(s.CD_ASEGURADORA)              ASEGURADORA,
  F_NM_USUARIO_SINIES(s.CD_USUARIO)               USUARIO,
  os.DSC_OBJETO                                   RECLAMANTE,
  o.DSC_OBJETO                                    TITULAR,
  i.ITEM,
  ic.NM_INCAPACIDAD,
  u.DSC_UBICACION                                 GRUPO,
  p.DSC_PLAN                                      PLAN,
  i.TP_SINIESTRO,
  i.VAL_DEDUCIBLE,
  i.VAL_SALDO_DED,
  rc.FC_HASTA - SYSDATE                           ES_VIGENTE_A,
  SYSDATE - rc.FC_DESDE                           ES_VIGENTE_B,
  rc.FC_DESDE,
  rc.FC_HASTA,
  i.DSC_DEDUCIBLE,
  r.NM_RAMO
FROM BRK_T_INCAP_SINIESTRO i, BRK_T_OBJ_SINIESTRO os, BRK_T_SINIESTRO s,
  BRK_T_INCAPACIDADES ic, BRK_T_CLI_GRUPO g, BRK_T_RAMOS_COTIZACION rc,
  brk_t_obj_cotizacion o, BRK_T_CLIENTES c, BRK_T_UBICACION u,
  BRK_T_PLANES p, BRK_T_RAMOS r
WHERE i.CD_COMPANIA = 1 AND i.CD_INC_SINIESTRO = 48231 AND s.CD_RECLAMO = 35822
      AND i.CD_OBJ_SINIESTRO = os.CD_OBJ_SINIESTRO
      AND os.CD_RECLAMO = s.CD_RECLAMO
      AND i.CD_INCAPACIDAD = ic.CD_INCAPACIDAD
      AND i.CD_COMPANIA = ic.CD_COMPANIA
      AND rc.CD_CLI_GRUPO = g.CD_CLI_GRUPO (+)
      AND s.CD_RAMO_COTIZACION = rc.CD_RAMO_COTIZACION
      AND s.CD_COMPANIA = rc.CD_COMPANIA
      AND s.cd_compania = o.cd_compania (+) AND s.cd_asegurado_tit = o.cd_asegurado (+)
      AND s.cd_ramo_cotizacion = o.cd_ramo_cotizacion (+)
      AND s.CD_CLIENTE = c.CD_CLIENTE
      AND o.CD_UBICACION = u.CD_UBICACION
      AND u.CD_PLAN = p.CD_PLAN
      AND rc.CD_RAMO = r.CD_RAMO AND rc.CD_COMPANIA = r.CD_COMPANIA;

--- amparos afectados
SELECT
  d.NM_COBERTURA,
  d.VAL_SINIESTRO,
  d.VAL_MINIMO,
  d.VAL_SINIESTRO - d.VAL_MINIMO VAL_CUBIERTO,
  d.VAL_DEDUCIBLE,
  d.VAL_TOTAL,
  d.FLG_COA,
  d.PCT_V_ASEG,
  d.VAL_MONTO_COA,
  d.VAL_FIJO,
  d.FLG_DED
FROM BRK_T_COB_DED_SINIESTRO d
WHERE d.CD_RECLAMO = 35823
      AND d.CD_COMPANIA = 1
      AND d.CD_INC_SINIESTRO = 48233
ORDER BY d.NM_COBERTURA;

-- facturas

SELECT
  g.DETALLE,
  g.NUM_RECIBO,
  g.FC_GASTO,
  g.VALOR,
  g.OBS_GASTO_VAM,
  d.NM_COBERTURA
FROM BRK_T_GASTOS_VAM g LEFT JOIN BRK_T_COB_DED_SINIESTRO d ON g.CD_COB_DED_SINIESTRO = d.CD_COB_DED_SINIESTRO
WHERE g.TIPO = 1
      AND g.CD_COMPANIA = 1
      AND d.CD_INC_SINIESTRO = 48233
ORDER BY g.FC_GASTO;

-- test cdReclamo/incap: 35822/48231 35823/48232 35823/48233
